### ISSUE TITLE
How to switch to Chinese language?

### ISSUE THREAD

**Issue by qq253498229** [gabriel-dehan/chronicondb-client#12]
I found Chinese data in (src/engine/data/1.30.0/sources/locale/CN). Is there any way to switch the page to Chinese display?

**Comment by qq253498229** [comment]
I tried to use CN folder instead EN, and then run yarn parse:all 1.30.0, it cause lots of error.
Such as 

```
PS D:\src\git\chronicondb-client> yarn parse:all 1.30.0
yarn run v1.22.11
$ ts-node -O "{ \"module\":\"commonjs\" }" src/engine/parsers/parseAll.ts --version 1.30.0

D:\src\git\chronicondb-client\src\engine\parsers\parseItems.ts:19
  const items: Item[] = rawItems.map((rawItem): Item => {
                                 ^
TypeError: Cannot read property 'flavor' of undefined
    at D:\src\git\chronicondb-client\src\engine\parsers\parseItems.ts:37:33
    at Array.map (<anonymous>)
    at Object.parseItems (D:\src\git\chronicondb-client\src\engine\parsers\parseItems.ts:19:34)
    at parseAll (D:\src\git\chronicondb-client\src\engine\parsers\parseAll.ts:27:3)
    at Object.<anonymous> (D:\src\git\chronicondb-client\src\engine\parsers\parseAll.ts:39:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module.m._compile (D:\src\git\chronicondb-client\node_modules\ts-node\src\index.ts:1043:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.require.extensions.<computed> [as .ts] (D:\src\git\chronicondb-client\node_modules\ts-node\src\index.ts:1046:12)
    at Module.load (internal/modules/cjs/loader.js:950:32)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by qq253498229** [comment]
I also replace EN to CN of src/engine/parsers/parseEnchants.ts(parseItems.ts,parseSets.ts), it also cause error above.

**Comment by qq253498229** [comment]
I fixed some error, and I found an error I do not know how can I fix:

```
PS D:\src\git\chronicondb-client> yarn build
yarn run v1.22.11
$ react-scripts build
Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
Failed to compile.

./src/hooks/useFilters.ts
  Line 0:  Parsing error: Cannot read property 'map' of undefined


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by gabriel-dehan** [comment]
Hey! I never handled other languages than english when I developed ChroniconDB, I thought about it but it required a lot more work so it is normal if you're having troubles :/ I am doing a lot of comparisons using english strings found in the files and that kind of things, which is probably why it's failing.

Although the error in `useFilters.ts` is kind of weird and I am not sure where it's coming from. 
If you want you can try opening a PR with your changes and I'll look at it when I'll have the time but that probably won't be very soon. I haven't had the time to update ChroniconDB in months and when I'll do there are a few big bugs that have been nagging me that I'll need to handle first.

**Comment by qq253498229** [comment]
> Hey! I never handled other languages than english when I developed ChroniconDB, I thought about it but it required a lot more work so it is normal if you're having troubles :/ I am doing a lot of comparisons using english strings found in the files and that kind of things, which is probably why it's failing.
> 
> Although the error in `useFilters.ts` is kind of weird and I am not sure where it's coming from.
> If you want you can try opening a PR with your changes and I'll look at it when I'll have the time but that probably won't be very soon. I haven't had the time to update ChroniconDB in months and when I'll do there are a few big bugs that have been nagging me that I'll need to handle first.

Thanks for reply.
I resolve these error, some of them maybe caused of my environment .
Now I can build it, but I found the navbar still English, is there some way to translate it ?
